const from = document.getElementById('form')
const username = document.getElementById('username')
const email = document.getElementById('username')
const password = document.getElementById('password')
const confirmPassword = document.getElementById('confirmPassword')